=== navikt/melosys-api/service/src/main/resources/dvh/a1-utstedt-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "type": "object",
  "description": "Skjema for melding om A1 utstedt fra Melosys",
  "examples": [
    {
      "saksnummer": "MEL-123",
      "behandlingId": 123,
      "serienummer": "MEL-123123",
      "aktorId": "1234567891234",
      "artikkel": "12.1",
      "periode": {
        "fom": "2020-10-09",
        "tom": "2020-11-09"
      },
      "utstasjoneringTilLand": "SE",
      "datoUtstedelse": "2020-10-09",
      "typeUtstedelse": "FØRSTEGANG",
      "meldingOpprettetTidspunkt": "2020-10-09T10:15:24.064758"
    }
  ],
  "required": [
    "serienummer",
    "saksnummer",
    "behandlingId",
    "aktorId",
    "artikkel",
    "periode",
    "utstasjoneringTilLand",
    "datoUtstedelse",
    "typeUtstedelse",
    "meldingOpprettetTidspunkt"
  ],
  "properties": {
    "serienummer": {
      "$id": "#/properties/serienummer",
      "type": "string",
      "description": "Eksplisitt id for attesten"
    },
    "saksnummer": {
      "$id": "#/properties/saksnummer",
      "type": "string",
      "maxLength": 99,
      "description": "Saksnummer i Melosys"
    },
    "behandlingId": {
      "$id": "#/properties/behandlingId",
      "type": "integer",
      "description": "Behandling-id i Melosys"
    },
    "aktorId": {
      "$id": "#/properties/aktorId",
      "type": "string",
      "maxLength": 13,
      "description": "Aktør-id til personen A1 utstedes for"
    },
    "artikkel": {
      "$id": "#/properties/artikkel",
      "type": "string",
      "description": "",
      "enum": [
        "11.3a",
        "11.3b",
        "11.4",
        "11.5",
        "12.1",
        "12.2",
        "13.1",
        "13.2",
        "13.3",
        "13.4",
        "16"
      ]
    },
    "periode": {
      "$id": "#/properties/periode",
      "type": "object",
      "description": "Perioden hvor A1 gjelder",
      "required": [
        "fom",
        "tom"
      ],
      "properties": {
        "fom": {
          "$id": "#/properties/periode/properties/fom",
          "type": "string",
          "format": "date",
          "description": "Periodens startdato (fra og med)"
        },
        "tom": {
          "$id": "#/properties/periode/properties/tom",
          "type": "string",
          "format": "date",
          "description": "Periodens sluttdato (til og med)"
        }
      },
      "additionalProperties": false
    },
    "utstasjoneringTilLand": {
      "$id": "#/properties/utstasjoneringTilLand",
      "type": ["string", "null"],
      "maxLength": 2,
      "description": "Land hvor aktør er utstasjonert (art. 12)"
    },
    "datoUtstedelse": {
      "$id": "#/properties/datoUtstedelse",
      "type": "string",
      "format": "date",
      "description": "Dato A1 er utstedt"
    },
    "typeUtstedelse": {
      "$id": "#/properties/typeUtstedelse",
      "type": "string",
      "description": "Hvilken type utstedelse av A1",
      "enum": [
        "FØRSTEGANG",
        "ENDRING",
        "ANNULLERING"
      ]
    },
    "meldingOpprettetTidspunkt": {
      "$id": "#/properties/meldingOpprettetTidspunkt",
      "type": "string",
      "format": "date-time",
      "description": "Tidspunkt da meldingen ble opprettet og lagt på kø"
    }
  },
  "additionalProperties": false
}

=== navikt/melosys-api/service/src/test/resources/dvh/a1-utstedt.json
{
  "saksnummer": "MEL-123",
  "behandlingId": 123,
  "serienummer": "MEL-123123",
  "aktorId": "1234567891234",
  "artikkel": "12.1",
  "periode": {
    "fom": "2020-10-09",
    "tom": "2020-11-09"
  },
  "utstasjoneringTilLand": "SE",
  "datoUtstedelse": "2020-10-09",
  "typeUtstedelse": "FØRSTEGANG",
  "meldingOpprettetTidspunkt": "2020-10-09T10:15:24.064758"
}
